name: database
description: An database implementation of the database interface.
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  postgres: ^2.6.1
  suivi_de_projets_back_data_source:
    path: ../suivi_de_projets_back_data_source
  uuid: ^3.0.6

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0